### PR TITLE
Add Support for Anthropic Messages

### PR DESCRIPTION
**Pull request by Hoekz**
Wanted support for the new Anthropic models on our on-prem version of BricksLLM. This seems to be functioning correctly to support the `/messages` endpoint that allows access to the Claude 3 models.

### CODE REVIEW

**Comment by spikelu2016** [comment]
Thanks for the update. Taking a look

**Comment by spikelu2016** [comment]
Another file called `handler` in `message` package also needs to get updated for counting the number of tokens from streaming responses.

For the anthropic text completion, we store the content of streaming responses in a field called  `content` and do the token counting asynchronously. You can test by checking whether the event generated by the streaming request contains the right `completion_token_count` inside postgres

**Comment by spikelu2016** [comment]
do you guys need bedrock anthropic integration as well?

**Comment by Hoekz** [comment]
Anthropic's documentation indicates that you don't need to count tokens while streaming messages since they include the token counts as part of the output unlike OpenAI...is setting the [completion token count](https://github.com/bricks-cloud/BricksLLM/pull/51/files#diff-097503bb4f6ea0ec214e71407a19b9f72fea177c48c54c7f1f15d6f62521dc9aR421) here not what matters?

We don't need Bedrock support at this time, we use BricksLLM as a sort of Sandbox / Playground for developers rather than for any actual applications.

**Comment by spikelu2016** [comment]
> Anthropic's documentation indicates that you don't need to count tokens while streaming messages since they include the token counts as part of the output unlike OpenAI...is setting the [completion token count](https://github.com/bricks-cloud/BricksLLM/pull/51/files#diff-097503bb4f6ea0ec214e71407a19b9f72fea177c48c54c7f1f15d6f62521dc9aR421) here not what matters?
> 
> We don't need Bedrock support at this time, we use BricksLLM as a sort of Sandbox / Playground for developers rather than for any actual applications.

 I see. Ignore what I said. I will proceed to testing the functionality

**Comment by spikelu2016** [comment]
released a new docker image v1.14.0 for this

**Pull request merged**
